# Generated by Django 5.2.8 on 2025-11-11 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vaccinationrecord',
            options={'ordering': ['-date_administered']},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_nurse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_vaccination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for appointment', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Current symptoms if any', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='vaccineapp.vaccine'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='List current medications', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='administering_facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='dose_number',
            field=models.IntegerField(default=1, help_text='Which dose in the series'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='reaction',
            field=models.CharField(choices=[('none', 'No Reaction'), ('mild', 'Mild Reaction'), ('moderate', 'Moderate Reaction'), ('severe', 'Severe Reaction')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='reaction_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('administered', 'Administered'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='administered', max_length=20),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='total_doses',
            field=models.IntegerField(default=1, help_text='Total doses required for this vaccine'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='booster_frequency',
            field=models.CharField(blank=True, help_text='e.g., Every 10 years', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='days_between_doses',
            field=models.IntegerField(blank=True, help_text='Days between doses', null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='route',
            field=models.CharField(blank=True, help_text='e.g., Intramuscular, Oral', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='site',
            field=models.CharField(blank=True, help_text='e.g., Upper arm, Thigh', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='storage_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.CharField(choices=[('routine', 'Routine Childhood'), ('travel', 'Travel'), ('seasonal', 'Seasonal'), ('special', 'Special Condition')], default='routine', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('vaccination', 'Vaccination'), ('consultation', 'Consultation'), ('checkup', 'Regular Checkup'), ('followup', 'Follow-up'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='vaccineapp.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any known allergies', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNK', 'Unknown')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_conditions',
            field=models.TextField(blank=True, help_text='List any medical conditions', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='vaccineapp.patient'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='vaccineapp.vaccine'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationrecord',
            unique_together={('patient', 'vaccine', 'dose_number')},
        ),
    ]
