# Generated by Django 5.2.8 on 2025-11-12 14:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0002_alter_appointment_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='booster_frequency',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='booster_required',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='target_diseases',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='doses_required',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.CharField(choices=[('combination', 'Combination Vaccine'), ('single', 'Single Antigen'), ('live', 'Live Attenuated'), ('inactivated', 'Inactivated')], default='single', max_length=20),
        ),
        migrations.CreateModel(
            name='VaccineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('doses_per_vial', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('lot_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('critical', 'Critical'), ('out_of_stock', 'Out of Stock')], default='in_stock', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='vaccineapp.vaccine')),
            ],
            options={
                'verbose_name_plural': 'Vaccine Inventories',
                'ordering': ['vaccine__name', 'expiration_date'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='inventory_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='vaccineapp.vaccineinventory'),
        ),
    ]
