# Generated by Django 5.2.8 on 2025-11-12 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0003_remove_vaccine_booster_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='age_groups',
            field=models.CharField(blank=True, help_text='Comma-separated age groups', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='age_groups',
            field=models.CharField(blank=True, help_text='Comma-separated age groups', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='storage_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='target_diseases',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='vaccine_type',
            field=models.CharField(blank=True, choices=[('combination', 'Combination Vaccine'), ('single', 'Single Antigen'), ('live', 'Live Attenuated'), ('inactivated', 'Inactivated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vaccineinventory',
            name='current_stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vaccineinventory',
            name='min_stock_level',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vaccineinventory',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='vaccineapp.vaccine'),
        ),
    ]
