# Generated by Django 6.0.2 on 2026-02-19 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0004_vaccine_age_groups_vaccineinventory_age_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['scheduled_date'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='vaccinationrecord',
            options={'ordering': ['-date_administered'], 'verbose_name': 'Vaccination Record', 'verbose_name_plural': 'Vaccination Records'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['name'], 'verbose_name': 'Vaccine', 'verbose_name_plural': 'Vaccines'},
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relationship_to_guardian',
            field=models.CharField(blank=True, help_text='e.g., Son, Daughter, Ward', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's credentials have been verified"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Medical license number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Area of specialization', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('parent', '👪 Parent/Guardian'), ('doctor', '👨\u200d⚕️ Doctor'), ('nurse', '👩\u200d⚕️ Nurse'), ('admin', '👑 Administrator')], default='parent', help_text='User role in the system - determines permissions and access levels', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='certificate_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='certificate_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='cdc_identifier',
            field=models.CharField(blank=True, help_text='CDC vaccine identifier', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='cvx_code',
            field=models.CharField(blank=True, help_text='CVX vaccine code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='received_by',
            field=models.CharField(blank=True, help_text='Staff who received the shipment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccineinventory',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date when vaccine was received', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__user_type__in': ['doctor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__user_type__in': ['nurse', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='administered_by',
            field=models.ForeignKey(blank=True, help_text='Medical professional who administered the vaccine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vaccineinventory',
            unique_together={('lot_number', 'vaccine')},
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the recommendation', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the recommendation')),
                ('recommendation_type', models.CharField(choices=[('restock', '📦 Restock Vaccine'), ('new_vaccine', '💉 New Vaccine Introduction'), ('dose_schedule', '📅 Dose Schedule Change'), ('storage', '❄️ Storage Requirement'), ('patient_outreach', '👥 Patient Outreach'), ('staff_training', '👨\u200d⚕️ Staff Training'), ('equipment', '🔧 Equipment Purchase'), ('policy', '📋 Policy Update'), ('expiring', '⚠️ Expiring Vaccine Alert'), ('other', '🔄 Other')], default='other', help_text='Type of recommendation', max_length=50)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High'), ('critical', '⚡ Critical')], default='medium', help_text='Priority level of this recommendation', max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('implemented', '🎯 Implemented'), ('archived', '📦 Archived')], default='pending', help_text='Current status of the recommendation', max_length=20)),
                ('recommended_quantity', models.IntegerField(blank=True, help_text='Recommended quantity to order (if restock)', null=True)),
                ('current_stock', models.IntegerField(blank=True, help_text='Current stock level at time of recommendation', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in USD', max_digits=10, null=True)),
                ('suggested_date', models.DateField(blank=True, help_text='Suggested date for implementation', null=True)),
                ('expiry_alert_date', models.DateField(blank=True, help_text='If related to expiring vaccines', null=True)),
                ('justification', models.TextField(blank=True, help_text='Business/medical justification for this recommendation')),
                ('benefits', models.TextField(blank=True, help_text='Expected benefits if implemented')),
                ('risks', models.TextField(blank=True, help_text='Potential risks if not implemented')),
                ('implementation_notes', models.TextField(blank=True, help_text='Notes on how to implement this recommendation')),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('review_date', models.DateTimeField(blank=True, help_text='When this recommendation was reviewed', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Supporting document (PDF, image, etc.)', null=True, upload_to='recommendation_attachments/')),
                ('reference_link', models.URLField(blank=True, help_text='Reference URL for more information', max_length=500, null=True)),
                ('is_automated', models.BooleanField(default=False, help_text='Whether this was generated automatically by the system')),
                ('trigger_reason', models.CharField(blank=True, help_text="What triggered this automated recommendation (e.g., 'low_stock', 'expiring_soon')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(blank=True, help_text='Related vaccine (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='vaccineapp.vaccine')),
                ('vaccine_inventory', models.ForeignKey(blank=True, help_text='Related inventory item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='vaccineapp.vaccineinventory')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='vaccineapp__status_cb6fa5_idx'), models.Index(fields=['recommendation_type'], name='vaccineapp__recomme_b134f3_idx'), models.Index(fields=['created_at'], name='vaccineapp__created_5190ab_idx')],
            },
        ),
    ]
