# Generated by Django
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):
    dependencies = [
        ('vaccineapp', '0005_alter_appointment_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the recommendation', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the recommendation')),
                ('recommendation_type', models.CharField(choices=[('restock', '📦 Restock Vaccine'), ('new_vaccine', '💉 New Vaccine Introduction'), ('dose_schedule', '📅 Dose Schedule Change'), ('storage', '❄️ Storage Requirement'), ('patient_outreach', '👥 Patient Outreach'), ('staff_training', '👨‍⚕️ Staff Training'), ('equipment', '🔧 Equipment Purchase'), ('policy', '📋 Policy Update'), ('expiring', '⚠️ Expiring Vaccine Alert'), ('other', '🔄 Other')], default='other', help_text='Type of recommendation', max_length=50)),
                ('priority', models.CharField(choices=[('low', '🟢 Low'), ('medium', '🟡 Medium'), ('high', '🔴 High'), ('critical', '⚡ Critical')], default='medium', help_text='Priority level of this recommendation', max_length=20)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('implemented', '🎯 Implemented'), ('archived', '📦 Archived')], default='pending', help_text='Current status of the recommendation', max_length=20)),
                ('recommended_quantity', models.IntegerField(blank=True, help_text='Recommended quantity to order (if restock)', null=True)),
                ('current_stock', models.IntegerField(blank=True, help_text='Current stock level at time of recommendation', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost in USD', max_digits=10, null=True)),
                ('suggested_date', models.DateField(blank=True, help_text='Suggested date for implementation', null=True)),
                ('expiry_alert_date', models.DateField(blank=True, help_text='If related to expiring vaccines', null=True)),
                ('justification', models.TextField(blank=True, help_text='Business/medical justification for this recommendation')),
                ('benefits', models.TextField(blank=True, help_text='Expected benefits if implemented')),
                ('risks', models.TextField(blank=True, help_text='Potential risks if not implemented')),
                ('implementation_notes', models.TextField(blank=True, help_text='Notes on how to implement this recommendation')),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('review_date', models.DateTimeField(blank=True, help_text='When this recommendation was reviewed', null=True)),
                ('attachment', models.FileField(blank=True, help_text='Supporting document (PDF, image, etc.)', null=True, upload_to='recommendation_attachments/')),
                ('reference_link', models.URLField(blank=True, help_text='Reference URL for more information', max_length=500, null=True)),
                ('is_automated', models.BooleanField(default=False, help_text='Whether this was generated automatically by the system')),
                ('trigger_reason', models.CharField(blank=True, help_text="What triggered this automated recommendation (e.g., 'low_stock', 'expiring_soon')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recommendations', to='auth.user')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to='auth.user')),
                ('vaccine', models.ForeignKey(blank=True, help_text='Related vaccine (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='vaccineapp.vaccine')),
                ('vaccine_inventory', models.ForeignKey(blank=True, help_text='Related inventory item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='vaccineapp.vaccineinventory')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['status', 'priority'], name='vaccineapp__status_9a19d8_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['recommendation_type'], name='vaccineapp__recomme_2a9cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['created_at'], name='vaccineapp__created_d2aee4_idx'),
        ),
    ]