# Generated by Django 6.0.2 on 2026-02-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0006_add_recommendation_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='vaccineapp__status_cb6fa5_idx',
            old_name='vaccineapp__status_9a19d8_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='vaccineapp__recomme_b134f3_idx',
            old_name='vaccineapp__recomme_2a9cfd_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendation',
            new_name='vaccineapp__created_5190ab_idx',
            old_name='vaccineapp__created_d2aee4_idx',
        ),
    ]
