# Generated by Django 6.0.2 on 2026-02-25 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0008_department_doctor_consultation_medicalrecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the vaccination event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the vaccination event')),
                ('scheduled_date', models.DateField(help_text='Date of the vaccination event')),
                ('start_time', models.TimeField(help_text='Start time of the event')),
                ('end_time', models.TimeField(help_text='End time of the event')),
                ('location', models.CharField(help_text='Location where vaccination will take place', max_length=200)),
                ('address', models.TextField(help_text='Full address of the location')),
                ('target_age_groups', models.CharField(blank=True, help_text='Comma-separated age groups targeted', max_length=200, null=True)),
                ('is_for_all', models.BooleanField(default=True, help_text='Whether this is for all patients')),
                ('max_capacity', models.IntegerField(default=0, help_text='Maximum number of patients (0 for unlimited)')),
                ('registered_count', models.IntegerField(default=0, help_text='Number of patients registered')),
                ('requires_registration', models.BooleanField(default=True, help_text='Whether patients need to register')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('is_published', models.BooleanField(default=False, help_text='Whether this schedule is published to patients')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for patients', null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone for inquiries', max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email for inquiries', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='vaccineapp.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccination Schedule',
                'verbose_name_plural': 'Vaccination Schedules',
                'ordering': ['-scheduled_date', 'start_time'],
            },
        ),
    ]
