# Generated by Django 6.0.2 on 2026-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='administered_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who administered the vaccine', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
