# Generated by Django 5.2.8 on 2026-09-28 09:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineapp', '0011_vaccinationrecord_administered_by_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity_level', models.CharField(choices=[('mild', '🟢 Mild'), ('moderate', '🟡 Moderate'), ('severe', '🔴 Severe')], default='mild', help_text='Baseline severity of this symptom — used by the rule engine', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive symptoms are hidden from reporting forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['severity_level', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='monitoring_duration_minutes',
            field=models.IntegerField(default=30, help_text='Default post-vaccination monitoring duration in minutes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('patient', '🧑 Patient'), ('healthcare_worker', '👨\u200d⚕️ Healthcare Worker'), ('admin', '👑 Administrator')], default='patient', help_text='User role in the system - determines permissions and access levels', max_length=20),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('yellow', '🟡 Attention'), ('red', '🔴 Urgent')], default='red', max_length=10)),
                ('status', models.CharField(choices=[('new', '🆕 New'), ('acknowledged', '👀 Acknowledged'), ('under_assessment', '🩺 Under Assessment'), ('resolved', '✅ Resolved'), ('follow_up_required', '📅 Follow-up Required')], default='new', max_length=25)),
                ('reason', models.TextField(help_text='What triggered this alert (copy of risk assessment reason)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_notes', models.TextField(help_text='What the healthcare worker observed')),
                ('action_taken', models.TextField(help_text="What was done in response (e.g., 'Observed for 20 more minutes', 'Referred to hospital')")),
                ('referral_facility', models.CharField(blank=True, help_text='If referred, which facility', max_length=200, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_response', to='vaccineapp.alert')),
                ('responded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Response',
                'verbose_name_plural': 'Clinical Responses',
                'ordering': ['-responded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('planned_duration_minutes', models.IntegerField(default=30, help_text='Planned monitoring duration in minutes (from vaccine default, can be overridden)')),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '🟢 Active'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled')], default='active', max_length=20)),
                ('current_level', models.CharField(choices=[('green', '🟢 Normal'), ('yellow', '🟡 Attention Required'), ('red', '🔴 Urgent Clinical Assessment Required')], default='green', help_text='Current risk level — updated automatically by the rule engine', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_sessions', to='vaccineapp.patient')),
                ('started_by', models.ForeignKey(help_text='Healthcare worker who started this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_monitoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('vaccination_record', models.OneToOneField(help_text='The vaccination that triggered this monitoring session', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_session', to='vaccineapp.vaccinationrecord')),
            ],
            options={
                'verbose_name': 'Monitoring Session',
                'verbose_name_plural': 'Monitoring Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='vaccineapp.monitoringsession'),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_type', models.CharField(choices=[('resolved', '✅ Resolved — no further action'), ('observed', '👀 Continued observation'), ('referred', '🏥 Referred to facility'), ('follow_up', '📅 Follow-up required'), ('admitted', '🛏️ Admitted'), ('other', '🔄 Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, help_text="If outcome is 'follow_up', when should it happen", null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_outcomes', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='vaccineapp.monitoringsession')),
            ],
            options={
                'verbose_name': 'Outcome',
                'verbose_name_plural': 'Outcomes',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('green', '🟢 Normal'), ('yellow', '🟡 Attention Required'), ('red', '🔴 Urgent Clinical Assessment Required')], max_length=10)),
                ('reason', models.TextField(help_text='Human-readable explanation of why this level was chosen')),
                ('triggered_rules', models.JSONField(blank=True, default=list, help_text='List of rule identifiers that fired (for audit / debugging)')),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='vaccineapp.monitoringsession')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='The risk assessment snapshot that triggered this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vaccineapp.riskassessment'),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="Unique device identifier, e.g., 'esp32-ward-1'", max_length=100)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Beats per minute (BPM)', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Blood oxygen saturation (%, 0–100)', null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Body temperature in °C', max_digits=4, null=True)),
                ('battery_level', models.IntegerField(blank=True, help_text='Device battery level (%, 0–100)', null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='Wi-Fi RSSI or similar (dBm)', null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='vaccineapp.monitoringsession')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_by_type', models.CharField(choices=[('patient', '🧑 Patient'), ('healthcare_worker', '👨\u200d⚕️ Healthcare Worker'), ('caregiver', '👪 Caregiver')], default='healthcare_worker', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional additional detail', null=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_by', models.ForeignKey(help_text='User who submitted this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_reports', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='vaccineapp.monitoringsession')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='vaccineapp.symptom')),
            ],
            options={
                'verbose_name': 'Symptom Report',
                'verbose_name_plural': 'Symptom Reports',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.AddIndex(
            model_name='monitoringsession',
            index=models.Index(fields=['status', 'current_level'], name='vaccineapp__status_43392e_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringsession',
            index=models.Index(fields=['patient', '-start_time'], name='vaccineapp__patient_7006c5_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['session', '-assessed_at'], name='vaccineapp__session_c1e394_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', '-created_at'], name='vaccineapp__status_883cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['level', 'status'], name='vaccineapp__level_6476b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['session', '-recorded_at'], name='vaccineapp__session_791bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['device_id'], name='vaccineapp__device__3063a9_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomreport',
            index=models.Index(fields=['session', '-reported_at'], name='vaccineapp__session_9d737e_idx'),
        ),
    ]
